### ISSUE TITLE
ghost 2.21.1 has new postinstall hook that's failing

### ISSUE THREAD

**Issue by drnic** [starkandwayne/ghost-for-cloudfoundry#11]
https://ci2.starkandwayne.com/teams/starkandwayne/pipelines/blog-starkandwayne/jobs/deploy-staging/builds/237

```
$ cp node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
   cp: cannot create regular file 'core/server/public/': No such file or directory
```

https://github.com/TryGhost/Ghost/blob/27dae4022c40242afbbc04e9297a54c0054f88f4/package.json#L35

comes from https://github.com/TryGhost/Ghost/commit/59c57a921

**Comment by allouis** [comment]
Looks like you need to change the postinstall script to copy to `current/core/server/public` I think, The package.json is at a different directory level in your fork

**Comment by drnic** [comment]
@allouis aah good find; yes it seems this was the first time `package.json` could not just be copied from `current/package.json` into `./package.json` without modification (or perhaps I did not run the `npm` commands that would have failed before the 2.21.1 release).

I can't find it now in ghost docs, but I swear that my pattern of putting the latest release in `./versions/v2.21.1` and symlink to it with `./current` was a best practise to allow easy upgrading.

Ok, will investigate how to "fix" `package.json` with alternate paths.
