### ISSUE TITLE
301 redirecting issue

### ISSUE THREAD

**Issue by GARENFEATHER** [starkandwayne/ghost-for-cloudfoundry#4]
hi there, just a question related to custom domain:
I mapped my domain using the same command as yours like
```
cf create-domain xxx.com
cf map-route myapp xxx.com --hostname yyy
```
all returned `OK`, but the subdomain point to my ghost blog is keeping 301 redirecting like this:
![301](https://media.discordapp.net/attachments/420095259125743637/463632542059331604/unknown.png)

both `xxx.com/yyy` and `yyy.xxx.com` run into the same 301-redirecting-issue but other apps don't
I found your custom domain mappings work well so have you ever encountered the same kinda bug?

Ghost version: 1.22.1(older for my own reason)

**Comment by drnic** [comment]
@GARENFEATHER for future-you and others, what was the resolution?

**Comment by GARENFEATHER** [comment]
@drnic sorry for the late response.
Guess that there is at least one nginx-layer as proxy fowarding your route to the application(e.g Ghost redirecting default: http://127.0.0.1:2368), the protocol they use here must be plain `http` not `https`. If your default `url` setting for Ghost was `https://xxx` then when you acess through `http://xxx` Ghost would redirect back to `https`, which trigger an endless redirect-between-http-and-https loop.
I was using cloudflare and chose `flexible` https strategy so whatever I did finally the direct access to server on cloudfoundry was through `http`.
I'm sure when you map a new route like `xxx.yy` to Ghost, the url setting will be `https://xxx.yy` instead of `http://xxx.yy`

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
