### ISSUE TITLE
Cleanup README since Ghost 1.0.0/mysql

### ISSUE THREAD

**Issue by GIANTCRAB** [starkandwayne/ghost-for-cloudfoundry#5]
Hi, it seems like the README is outdated. I've taken a look at the configs and setup etc and found that its no longer using postgresql but rather mysql.

If you could confirm this issue, I would be happy to help update it and send in a PR to update the README.

Thanks!

**Comment by drnic** [comment]
Sorry yes readme is outdated if mentions postgresql. The Ghost team decided to abandon PG support at v1.0.0, and ghost-for-cloudfoundry is now beyond v1.0.0 (and is automatically self-upgrading as new versions are released).

I'll leave this issue open until I/someone does a round of improvements to readme.

**Comment by GIANTCRAB** [comment]
I created PR #6 but I'm actually experiencing some issues with deploying it. (Which I'll create another issue for)

**Comment by drnic** [comment]
I've updated the READMe to point to https://ci2.starkandwayne.com/teams/starkandwayne/pipelines/blog-starkandwayne?groups=blog-starkandwayne as the new home of the CI which upgrades this repo (and deploys to staging -> prod for https://www.starkandwayne.com/blog/)
